// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace photoGallary.Migrations
{
    [DbContext(typeof(photoGallarynewPhotoContext))]
    [Migration("20211007122628_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("photoGallery.newPhoto.newPhoto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("captureDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.Property<string>("size")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("newPhoto");
                });
#pragma warning restore 612, 618
        }
    }
}
